version: '2'
services:
    hairnow-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/hairnow/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hairnow
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
